apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crds-rabbitmq
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crds-rabbitmq
    spec:
      containers:
        - name: crds-rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
            - containerPort: 15672
