apiVersion: v1
kind: Service
metadata:
  name: crds-rabbitmq-service
  labels:
    app: crds-rabbitmq-service
spec:
  ports:
  - name: queue
    port: 5672
    targetPort: 5672
  - name: admin
    port: 15672
    targetPort: 15672
  type: LoadBalancer
  selector:
    app: crds-rabbitmq
